#!/bin/sh

env_file="env.sh"
config_file="config.sh"

die() {
    echo "init-root: Error: $*"
    exit 1
}

show_help() {
    cat <<EOF
Usage: init-root <CONFIG> [OPTIONS...]
       init-root [-l|--list]
       init-root [-h|--help]

  Initializes current directory as jagen build root.

SYNOPSIS:

  The script will put an environment file '$env_file' and a configuration file
  '$config_file' in the current directory. The environment file should be
  sourced into the working shell before issuing any other jagen commands. The
  configuration file is sourced by a generator and a build system.

  Jagen will create and remove few directories inside the build root depending
  on the selected configuration and commands given, so it is not safe to store
  important data there. Also initializing jagen's own project directory as
  build root is not supported. It is recommended to use separate directory for
  every configuration and do not mix shell environments from different build
  roots.

OPTIONS:

  -a, --flags   Set a space-separated list of default flags.
  -l, --list    List available configuration templates.
  -h, --help    Print this help message.

EXAMPLES:

    mkdir -p ~/work/root-ast100
    cd ~/work/root-ast100
    "<jagen_dir>/init-root" ast100 -a flag1 flag2
    . ./$env_file
    jagen run target1 target2
    exit

  For subsequent invocations:

    cd ~/work/root-ast100
    . ./$env_file
    jagen run target3 target4

EOF
}

list_configs() {
    cd "$jagen_dir/lib/config"
    for cfg_dir in *; do
        echo $cfg_dir
    done
}

write_env() {
    cat >"$env_file" <<EOF
#!/bin/sh

jagen_relative_dir="$jagen_dir"

jagen_dir=\$(cd "\$jagen_relative_dir"; pwd -P)
jagen_root=\$(pwd -P)
export jagen_dir jagen_root

. "\$jagen_dir/lib/env.sh"; sts=\$?
if [ \$sts != 0 ]; then
    echo "Error: failed to load jagen environment"
    return \$sts
fi

add_PATH "\$jagen_private_dir/bin"
add_PATH "\$jagen_dir/bin"
EOF
}

write_config() {
    cat >"$config_file" <<EOF
# jagen_dir  - refers to the jagen project directory.
# jagen_root - refers to the current build root (where this file is located).

# Environment overlays used by this build root.
jagen_overlays="$jagen_overlays"

# Toplevel working directory.
# Note: setting relative path allows to source this environment both from
# outside and inside the chrooted container.
jagen_base_dir=\$(real_path "\$jagen_dir/..")

# A directory containing software distributions and patches.
jagen_dist_dir="\$jagen_base_dir/dist"

# A directory where source packages will be checked out.
jagen_src_dir="\$jagen_base_dir/src"

# A directory where build products will be stored.
jagen_build_dir="\$jagen_root/build"

# A directory containing target toolchain.
jagen_toolchain_dir="$jagen_toolchain_dir"

# A directory containing SDK.
jagen_sdk_dir="$jagen_sdk_dir"

# Space separated list of optional features.
#   debug   - build debugging tools
#   ccache  - wrap compilation commands with ccache
#   offline - skip network operations
jagen_flags="$jagen_flags"

# Space separated list of package names excluded from cleaning and updating.
# Example: jagen_source_exclude="chicken karaoke-player"
jagen_source_exclude=""

# Global build type.
# Available values: Release|RelWithDebInfo|Debug
jagen_build_type="Release"
EOF
}

parse_command_line() {
    local arg='config'

    while [ $# -gt 0 ]; do
        case $1 in
            -a|--flags)
                arg='flags' ;;
            -l|--list)
                list_configs; exit 0 ;;
            -h|--help)
                show_help; exit 0 ;;
            -*)
                die "invalid argument: $1" ;;
            *)
                case $arg in
                    config)
                        jagen_config="$1"; arg='' ;;
                    flags)
                        if [ "$jagen_flags" ]; then
                            jagen_flags="$jagen_flags $1"
                        else
                            jagen_flags="$1"
                        fi ;;
                    *)
                        die "unexpected argument: $1"
                        ;;
                esac ;;
        esac
        shift
    done
}

jagen_dir=$(dirname $0)
jagen_root=''
jagen_config=''
jagen_flags=''

if [ $# = 0 ]; then
    show_help
    exit 0
fi

parse_command_line "$@"

if ! [ "$jagen_config" ]; then
    die "no configuration template specified"
fi

jagen_config_dir="$jagen_dir/lib/config/$jagen_config"

if ! [ -d "$jagen_config_dir" ]; then
    die "no such configuration template: $jagen_config"
fi

. "$jagen_config_dir/env.sh" || exit

write_env || exit
write_config "$config_file" || exit
. ./env.sh || exit
jagen refresh
