#!/bin/sh

set -eu

env_file="env.sh"
config_file="config.sh"

jagen_dir=$(dirname "$0")

message() {
    echo init-project: $*
}

die() {
    message $*
    exit 1
}

show_usage() {
    cat <<EOF
Usage: init-project [OPTIONS...] [--] [LAYERS...]

  Initializes current directory as a Jagen project.

SYNOPSIS:

  The script will put an environment file 'env.sh' and a configuration file
  'config.sh' in the current directory. The environment file should be sourced
  into the working shell before issuing any other Jagen commands. The config
  file contains project-specific settings and is sourced by the build system.

OPTIONS:

  -a          add the flag to jagen_flags
  -i          add the directory to jagen_include_path
  -f          force to initialize non-empty directory
  -h, --help  show this usage information

EOF
}

write_env() {
    cat >"$env_file" <<EOF
#!/bin/sh

jagen_relative_dir="$jagen_dir"

jagen_dir=\$(cd "\$jagen_relative_dir"; pwd -P)
jagen_project_dir=\$(pwd -P)
export jagen_dir jagen_project_dir

. "\$jagen_dir/env.sh"; sts=\$?
if [ \$sts != 0 ]; then
    echo "Error: failed to load jagen environment"
    return \$sts
fi

add_PATH "\$jagen_dir/bin"
add_PATH "\$jagen_project_dir/bin"
EOF
}

write_config() {
    cat >"$config_file" <<EOF
# jagen_dir         - refers to the jagen source directory
# jagen_project_dir - refers to the current project directory

# A list of directories containing layers used by this project.
# The list items should be newline (\\n) or tab (\\t) separated because normal
# spaces (including the indentation) are assumed to be the part of the pathname.
jagen_layers="${jagen_layers-}"

# A list of directories which will be used to resolve unqualified layer names.
jagen_include_path="${jagen_include_path-}"

# A directory for package sources.
jagen_src_dir="\$jagen_project_dir/src"

# A directory for downloaded distribution files.
jagen_dist_dir="\$jagen_project_dir/dist"

# Space separated list of optional features.
#   ccache  - wrap compilation commands with ccache
#   debug   - build debugging tools
#   devenv  - enable features pertinent to development environment
#   offline - skip network operations
jagen_flags="${jagen_flags-}"

# Space separated list of package names excluded from cleaning and updating.
jagen_source_exclude=""

# The default build profile: release|debug|release_with_debug
jagen_build_profile="release"
EOF
}

parse_command_line() {
    local eoa=

    while [ $# -gt 0 ]; do
        case $1 in
            --) eoa=1 ;;
            -*) if [ "${eoa:-}" ]; then
                    init_jagen_layers="${init_jagen_layers-} $1"
                else
                    case $1 in
                        -a|--flag)
                            jagen_flags="${jagen_flags-} $2"; shift ;;
                        -i|--include)
                            jagen_include_path="${jagen_include_path-} $2"; shift ;;
                        -f|--force)
                            use_force=1 ;;
                        -h|--help)
                            show_usage; exit 0 ;;
                        *)
                            die "invalid option: $1"
                    esac
                fi ;;
             *) init_jagen_layers="${init_jagen_layers-} $1" ;;
        esac
        shift
    done

    jagen_flags=${jagen_flags+${jagen_flags# }}
    jagen_include_path=${jagen_include_path+${jagen_include_path# }}
    init_jagen_layers=${init_jagen_layers+${init_jagen_layers# }}
}

do_init() {
    parse_command_line "$@"

    if [ -z "${use_force-}" -a "$(ls -A)" ]; then
        die "not initializing non-empty directory without force"
    fi

    # construct newline-separated list of layers -- it looks prettier in
    # the config and allows having spaces in the paths
    jagen_layers="
"
    for layer in ${init_jagen_layers-}; do
        jagen_layers="${jagen_layers-}$layer
"
    done

    write_env || exit
    write_config "$config_file" || exit

    if ! [ -f "lib/rules.lua" ]; then
        mkdir -p lib
        cat >"lib/rules.lua" <<EOF
-- local rules for $(basename "$PWD")
EOF
fi

    . ./env.sh || exit
    jagen refresh
}

do_init "$@"
