#!/bin/sh

print_help() {
    echo "Usage: $0 <COMMAND> <OPTIONS>...
Generates a build system.

Commands:
  help		print this help message
  refresh	regenerate build system"
}

export ja_root="$(realpath $(dirname $0))"

cd "$ja_root"

. lib/env.sh
use_env tools

case $1 in
    help)
        print_help
        ;;
    refresh)
        if ! $(which chibi-scheme >/dev/null 2>&1); then
            for s in unpack build install; do
                bin/pkg.sh chibi-scheme $s tools \
                    || die "Failed to $s chibi-scheme"
            done
        fi
        exec $ja_bin generate build.ninja "$ja_lib_dir/rules.scm"
        ;;
    build)
        shift
        exec ninja "$@"
        ;;
    rebuild)
        shift
        target_path="$1"
        shift
        rm -f "$target_path"
        ninja "$@"
        cat "${target_path}.log"
        ;;
esac
