package {
    source = 'cairo-1.14.2.tar.xz',
    build = {
        type    = 'GNU',
        options = {
            '--disable-static',
            '--disable-gtk-doc',
            '--disable-gtk-doc-html',
            '--disable-valgrind',
            '--disable-xlib',
            '--disable-xlib-xrender',
            '--disable-xcb',
            '--disable-xlib-xcb',
            '--disable-xcb-shm',
            '--disable-qt',
            '--disable-quartz',
            '--disable-quartz-font',
            '--disable-quartz-image',
            '--disable-win32',
            '--disable-win32-font',
            '--disable-skia',
            '--disable-os2',
            '--disable-beos',
            '--disable-drm',
            '--disable-gallium',
            '--disable-png',
            '--disable-gl',
            '--disable-glesv2',
            '--disable-cogl',
            '--disable-directfb',
            '--disable-vg',
            '--disable-egl',
            '--disable-glx',
            '--disable-wgl',
            '--disable-script',
            '--enable-ft',
            '--disable-fc',
            '--disable-ps',
            '--disable-pdf',
            '--disable-svg',
            '--disable-test-surfaces',
            '--disable-tee',
            '--disable-xml',
            '--enable-pthread=auto',
            '--disable-gobject',
            '--disable-trace',
            '--disable-interpreter',
            '--disable-symbol-lookup',
            '--without-x'
        },
        libs = { 'cairo' }
    }
}
