#!/bin/sh

export jagen_ccache_bin_dir="/usr/lib/ccache/bin"

# This should allow sharing cache between different roots.
export CCACHE_BASEDIR="$jagen_root"

# The default check uses compiler's mtime and size, which can cause false
# misses due to autogenerated wrappers for some SDKs.
export CCACHE_COMPILERCHECK="content"

# Performance improvements (read the manual).
export CCACHE_SLOPPINESS="include_file_mtime,time_macros"
