#!/bin/sh

export jagen_ccache="${jagen_ccache:-ccache}"

# This should allow sharing cache between different roots.
export CCACHE_BASEDIR="$HOME"

# The default check uses compiler's mtime and size, which can cause false
# misses due to autogenerated wrappers for some SDKs.
export CCACHE_COMPILERCHECK="content"

# Performance improvements (read the manual).
export CCACHE_SLOPPINESS="file_stat_matches,include_file_mtime,time_macros"
